version: 2
workflows:
  version: 2
  release:
    jobs:
    - release:
        filters:
          branches:
            only: master
jobs:
  release:
    docker:
    - image: docker:stable-git
    environment:
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      ECR: 038620613384.dkr.ecr.us-east-1.amazonaws.com
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Install Dependencies
        command: |
          apk add --no-cache py-pip
          pip install awscli
    - run:
        name: Login to ECR
        command: |
          eval $(aws ecr get-login --no-include-email)
    - run:
        name: Build ES-Loader Image
        command: |
          docker build -t ${ECR}/tenjin/requestbin:latest -t ${ECR}/tenjin/requestbin:${CIRCLE_SHA1} .
    - run:
        name: Publish Image to ECR
        command: |
          docker push ${ECR}/tenjin/requestbin:${CIRCLE_SHA1}
          docker push ${ECR}/tenjin/requestbin:latest
