---
apiVersion: v1
kind: Service
metadata:
  namespace: requestbin
  name: requestbin
  labels:
    app: requestbin
spec:
  selector:
    app: requestbin
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
