---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: requestbin
  name: requestbin
  labels:
    app: requestbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestbin
  template:
    metadata:
      labels:
        component: requestbin
    spec:
      containers:
      - name: requestbin
        image: 038620613384.dkr.ecr.us-east-1.amazonaws.com/tenjin/requestbin:latest
        resources:
          requests:
            cpu: 10m
            memory: 150Mi
          limits:
            cpu: 500m
            memory: 250Mi
        ports:
        - containerPort: 80
          name: http
